# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConversationObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, question: str=None, answer: object=None):  # noqa: E501
        """ConversationObject - a model defined in Swagger

        :param question: The question of this ConversationObject.  # noqa: E501
        :type question: str
        :param answer: The answer of this ConversationObject.  # noqa: E501
        :type answer: object
        """
        self.swagger_types = {
            'question': str,
            'answer': object
        }

        self.attribute_map = {
            'question': 'question',
            'answer': 'answer'
        }

        self._question = question
        self._answer = answer

    @classmethod
    def from_dict(cls, dikt) -> 'ConversationObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConversationObject of this ConversationObject.  # noqa: E501
        :rtype: ConversationObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question(self) -> str:
        """Gets the question of this ConversationObject.


        :return: The question of this ConversationObject.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question: str):
        """Sets the question of this ConversationObject.


        :param question: The question of this ConversationObject.
        :type question: str
        """

        self._question = question

    @property
    def answer(self) -> object:
        """Gets the answer of this ConversationObject.


        :return: The answer of this ConversationObject.
        :rtype: object
        """
        return self._answer

    @answer.setter
    def answer(self, answer: object):
        """Sets the answer of this ConversationObject.


        :param answer: The answer of this ConversationObject.
        :type answer: object
        """

        self._answer = answer
