# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ItemComponent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, component_name: str=None, description: str=None):  # noqa: E501
        """ItemComponent - a model defined in Swagger

        :param component_name: The component_name of this ItemComponent.  # noqa: E501
        :type component_name: str
        :param description: The description of this ItemComponent.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'component_name': str,
            'description': str
        }

        self.attribute_map = {
            'component_name': 'componentName',
            'description': 'description'
        }

        self._component_name = component_name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'ItemComponent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ItemComponent of this ItemComponent.  # noqa: E501
        :rtype: ItemComponent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def component_name(self) -> str:
        """Gets the component_name of this ItemComponent.


        :return: The component_name of this ItemComponent.
        :rtype: str
        """
        return self._component_name

    @component_name.setter
    def component_name(self, component_name: str):
        """Sets the component_name of this ItemComponent.


        :param component_name: The component_name of this ItemComponent.
        :type component_name: str
        """

        self._component_name = component_name

    @property
    def description(self) -> str:
        """Gets the description of this ItemComponent.


        :return: The description of this ItemComponent.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ItemComponent.


        :param description: The description of this ItemComponent.
        :type description: str
        """

        self._description = description
