---
swagger: "2.0"
info:
  description: "Documentation for project STudent."
  version: "1.0.0"
  title: "STudent"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "classify"
  description: "Image detection and text recognition"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "teaching"
  description: "Teaching endpoint"
schemes:
- "https"
- "http"
paths:
  /classify/classifyImage:
    post:
      tags:
      - "classify"
      summary: "Classify the image"
      description: ""
      operationId: "classify_image"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Base64 image"
        required: true
        schema:
          $ref: "#/definitions/IMGFile"
      responses:
        "200":
          description: "Image classification"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ItemClassification"
      security:
      - petstore_auth:
        - "read:pets"
      x-swagger-router-controller: "swagger_server.controllers.classify_controller"
  /classify/classifyText:
    post:
      tags:
      - "classify"
      summary: "Classify the text"
      description: ""
      operationId: "classify_text"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Conversation"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/ConversationObject"
      responses:
        "200":
          description: "Image classification"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ItemClassification"
      security:
      - petstore_auth:
        - "read:pets"
      x-swagger-router-controller: "swagger_server.controllers.classify_controller"
  /classify/getInfo/{itemName}:
    get:
      tags:
      - "classify"
      summary: "Get info about the object"
      description: ""
      operationId: "get_info"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "itemName"
        in: "path"
        description: "The unique name of the item"
        required: true
        type: "string"
      responses:
        "200":
          description: "Item components"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ItemComponent"
      x-swagger-router-controller: "swagger_server.controllers.classify_controller"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  IMGFile:
    type: "object"
    properties:
      image_b64:
        type: "string"
        example: "Base64-encoded image"
    example:
      image_b64: "Base64-encoded image"
  ItemClassification:
    type: "object"
    properties:
      found:
        type: "boolean"
        example: true
      class:
        type: "string"
        example: "Mouse"
      score:
        type: "number"
        example: 0.95999999999999996447286321199499070644378662109375
      imgEndpoint:
        type: "string"
        example: "https://www.st.com/content/ccc/fragment/application_related/end_app_information/end_app_block_diagram/group0/2e/a5/77/2f/ba/2c/41/ea/mobile_pos_image/files/mobile_pos.jpg/_jcr_content/translations/en.mobile_pos.jpg"
    example:
      found: true
      class: "Mouse"
      imgEndpoint: "https://www.st.com/content/ccc/fragment/application_related/end_app_information/end_app_block_diagram/group0/2e/a5/77/2f/ba/2c/41/ea/mobile_pos_image/files/mobile_pos.jpg/_jcr_content/translations/en.mobile_pos.jpg"
      score: 0.95999999999999996447286321199499070644378662109375
  ItemComponent:
    type: "object"
    properties:
      componentName:
        type: "string"
        example: "BALF-NRG-02D3"
      description:
        type: "string"
        example: "Programmable Bluetooth&reg; LE 5.2 Wireless SoC"
    example:
      componentName: "BALF-NRG-02D3"
      description: "Programmable Bluetooth&reg; LE 5.2 Wireless SoC"
  ConversationObject:
    type: "object"
    properties:
      question:
        type: "string"
        example: "Does ST produce mices?"
      answer:
        type: "object"
        properties:
          response:
            type: "string"
            example: "Yes, we produce mices"
          items:
            type: "array"
            items:
              $ref: "#/definitions/ItemClassification"
